### ISSUE TITLE
Результат не должен выводится до того, как будет вычислен

### ISSUE THREAD

**Issue by Anatoliyphp** [RomanKazantsev13/back-end#2]
https://github.com/RomanKazantsev13/back-end/blob/4e0580bcfc6481b9815d28a68e5a64cf1f38617e/Calculator/Program.cs#L130

**Comment by RomanKazantsev13** [comment]
А почему нет? Данный калькулятор сделан на подобии того калькулятора, который находится у нас в телефоне. И как только ты входишь в приложение, ты сразу наблюдаешь результат и после можешь выполнять различные действия (ввести новое число,  прибавить и т.д.)

**Comment by Anatoliyphp** [comment]
Раз приложение задумано таким образом, нужно создать отдельный класс калькулятора, который будет иметь нужные операции и состояние в виде результата.
